# Generated by Django 2.1.5 on 2019-02-07 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landin_page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage_content',
            name='first_block_text',
        ),
        migrations.RemoveField(
            model_name='homepage_content',
            name='second_block_text',
        ),
        migrations.RemoveField(
            model_name='homepage_content',
            name='third_block_text',
        ),
        migrations.AddField(
            model_name='homepage_content',
            name='first_block_h1',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='homepage_content',
            name='first_block_h2',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='homepage_content',
            name='first_block_p',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='homepage_content',
            name='second_block_h1',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='homepage_content',
            name='second_block_p',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='homepage_content',
            name='third_block_h1',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='homepage_content',
            name='third_block_p',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='homepage_content',
            name='second_block_link',
            field=models.URLField(default=0),
        ),
        migrations.AlterField(
            model_name='homepage_content',
            name='third_block_link',
            field=models.URLField(default=0),
        ),
    ]
