# Generated by Django 2.1.5 on 2019-01-09 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('attachment', models.FileField(upload_to='')),
                ('picture', models.ImageField(upload_to='')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('valid_till', models.DateTimeField()),
                ('slug', models.SlugField(max_length=40, unique=True)),
            ],
        ),
    ]
