# Generated by Django 2.1.5 on 2019-01-09 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='attachment',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='notice',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='notice',
            name='slug',
            field=models.SlugField(default='', max_length=40, unique=True),
        ),
    ]
