# Generated by Django 2.1.5 on 2019-01-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard', '0002_auto_20190109_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='notice',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='notice',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=40, unique=True),
        ),
    ]
