# Generated by Django 2.1.5 on 2019-01-17 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard', '0003_auto_20190116_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
