# Generated by Django 2.1.5 on 2019-01-17 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard', '0004_auto_20190117_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='notification_files/'),
        ),
    ]
