# Generated by Django 2.1.5 on 2019-01-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard', '0005_auto_20190117_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
